### ISSUE TITLE
KNXGlobalContext_READ variable number of objects and problem in finding a specific group Address

### ISSUE THREAD

**Issue by robertotarga** [Supergiovane/KNXUltimate#4]
Hi Massimo,
thank you for bringing to the Node-red community the fabulous KNXUltimate node. I found some issues regarding the behaviour of KNXGlobalContext_READ

I expected that KNXGlobalContext_READ contained all group addresses of the ETS Project. I have some 68 GA in my projects, but observing after some time the global variable from NR Global Context Data  I see that the number of objects  is lower, i.e. 10-20, not constant and varies from time to time. 

The problem is that, if you want to find a GA not in KNXGlobalContext_READ, the node will not send any object:

let GroupAddresses = global.get("KNXContextProserv_READ") || [];
let ga = GroupAddresses.find(a => a.address === "3/1/10");
node.send(ga)

no ga object is sent if "3/1/10" is not present in KNXContextProserv_READ

After working sometime using  the above code in a node suddenly KNXContextProserv_READ got all its 68 GA and the ga 3/1/10 was found. What it's still unclear is why for some time the number of items in  KNXContextProserv_READ was so low?

KNXUltimate v. 1.4.6
NR v. 3.0.2

**Comment by Supergiovane** [comment]
Hi Roberto. 
This is the expected behavior. The global context node collects the values that are read from bus. Until the group address doesn’t transit over the bus, the node is unaware of it. 
You’ve imported the ETS file, so you’re expecting all group addresses to be present, but they are unuseful if the respective values aren’t present. 
You could send a read request to the bus, whenever nodered starts, using a knx node set in universal mode.

**Comment by robertotarga** [comment]
Ok Massimo, thank you for the prompt reply.
I wrongly assumed that the GlobalContex node would somehow force the reading of all addresses in ETS import file, but it’s not the case. I will take care of needed ga forcing a readstatus from the device node set as universal.

Ciao
Roberto

Inviato da iPad
